### ISSUE TITLE
Define a github workflow that publishes routerFS to maven central

### ISSUE THREAD

**Issue by talSofer** [treeverse/hadoop-router-fs#13]
Create the RouterFS counterpart for https://github.com/treeverse/lakeFS/blob/master/.github/workflows/publish-hadoop-lakefs.yaml

### Definition of done 
- There is a github workflow that publishes RouterFS to maven central 
- The workflow is triggered manually

**Comment by Jonathan-Rosenberg** [comment]
Currently, RouterFS is on pause.
If needed we'll reopen this issue
